GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsInVzZXJuYW1lIjoiU3VwZXJBZG1pbiIsImVtYWlsIjoiU0FkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJTdXBlciBBZG1pbiIsImlhdCI6MTY1ODk5NzM2NSwiZXhwIjoxNjU5MDgzNzY1fQ.H9xbtrL_Ue_Bz38qLEvCRkXu9pBtYpDcLhIoOo_5FSE

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username" : "SuperAdmin",
    "email" : "SAdmin@gmail.com",
    "role" : "Super Admin",
    "password" : "Sadmin",
    "confirmPassword" : "Sadmin"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username" : "SuperAdmin",
    "password" : "Sadmin"
}