GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsInVzZXJuYW1lIjoiU3VwZXJBZG1pbiIsImVtYWlsIjoiU0FkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJTdXBlciBBZG1pbiIsImlhdCI6MTY1OTA4OTMwOCwiZXhwIjoxNjU5MTc1NzA4fQ.sW65LCFp-seoOXCKNQsgTLtJ4v609mCJVrW-pZ6N9xA

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username" : "SuperAdmin",
    "email" : "SAdmin@gmail.com",
    "role" : "Super Admin",
    "password" : "Sadmin",
    "confirmPassword" : "Sadmin"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username" : "SuperAdmin",
    "password" : "Sadmin"
}